version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
      - cache
    ports:
      - "${APP_PORT}:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=cache
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - user_service_network

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - user_service_network

  cache:
    image: redis:7.0-alpine
    volumes:
      - cache_data:/data
    networks:
      - user_service_network

volumes:
  db_data:
    name: db_data
  cache_data:
    name: cache_data

networks:
  user_service_network:
    driver: bridge