spring:
  application:
    name: impl

# Postgres database connection settings
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username : postgres
    password: Tim4ik13
    driver-class-name: org.postgresql.Driver

# Liquibase settings
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    # automatic migration applying
    enabled: true
