name: User Service CI Pipeline

on:
  push:
    branches: [ main, ci-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outcome }}

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
      
    - name: JDK setup
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: ./impl/pom.xml

    - name: Building project
      id: build
      run: mvn compile -q -DskipTests
      working-directory: ./impl

    - name: Upload compiled classes
      uses: actions/upload-artifact@v4
      with:
        name: compiled-classes
        path: ./impl/target/classes
        
  tests:
    name: Testing
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.build-status == 'success'
    
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
  
    - name: JDK setup
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: ./impl/pom.xml

    - name: Downloading compiled classes
      uses: actions/download-artifact@v4
      with:
        name: compiled-classes
        path: ./impl/target/classes
        
    - name: Check Docker
      run: docker info
        
    - name: Tests with JaCoCo coverage
      run: mvn verify -q
      working-directory: ./impl

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tests-results
        path: ./impl/target/surefire-reports/