name: User Service CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outcome }}

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
      
    - name: JDK setup
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: ./impl/pom.xml

    - name: Building project
      id: build
      run: mvn compile -q -DskipTests
      working-directory: ./impl

    - name: Upload compiled classes
      uses: actions/upload-artifact@v4
      with:
        name: compiled-classes
        path: ./impl/target/classes
        
  tests:
    name: Testing
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.build-status == 'success'
    
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
  
    - name: JDK setup
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: ./impl/pom.xml

    - name: Downloading compiled classes
      uses: actions/download-artifact@v4
      with:
        name: compiled-classes
        path: ./impl/target/classes
        
    - name: Checking Docker state
      run: docker info
        
    - name: Tests with JaCoCo coverage
      run: mvn verify -q
      working-directory: ./impl

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tests-results
        path: ./impl/target/surefire-reports/
        
    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=TimofeyCheberukInno_UserService \
        -Dsonar.organization=timofeycheberukinno \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.branch.name=${GITHUB_REF_NAME} \
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      working-directory: ./impl