name: User Service CI Pipeline

on:
  push:
    branches: [ main, ci-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    outputs:
      build-status: ${{ steps.build.outcome }}

    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v4
      
    - name: JDK setup
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: ./impl/pom.xml

    - name: Build project
      id: build
      run: mvn compile -q -DskipTests
      working-directory: ./impl

    - name: Upload compiled classes
      uses: actions/upload-artifact@v4
      with:
        name: compiled-classes
        path: ./impl/target/classes
        
  tests:
    name: Testing
    runs-on: windows-latest
    needs: build
    if: needs.build.outputs.build-status == 'success'

    steps:
    - name: Проверка кода из репозитория
      uses: actions/checkout@v4
  
    - name: JDK setup
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: ./impl/pom.xml

    - name: Download compiled classes
      uses: actions/download-artifact@v4
      with:
        name: compiled-classes
        path: ./impl/target/classes

    - name: Run tests
      run: mvn test -q
      working-directory: ./impl

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tests-results
        path: ./impl/target/surefire-reports/
